### ISSUE TITLE
Femnist: IndexError: list index out of range. 

### ISSUE THREAD

**Issue by colin-byrneireland** [TalwalkarLab/leaf#22]
When I run python main.py -dataset femnist -model cnn -lr 0.06 --minibatch 0.1 --clients-per-round 3 --num-rounds 20 

I get the following 
![image](https://user-images.githubusercontent.com/44531236/71667242-2b01c980-2d5c-11ea-86c7-178f1e246d38.png)

======================End of Report==========================
Clients in Total: 0
--- Random Initialization ---
--- Round 1 of 20: Training 3 Clients ---
Traceback (most recent call last):
  File "main.py", line 186, in <module>
    main()
  File "main.py", line 87, in main
    server.update_model()
  File "/mnt/c/ul/ai/Thesis/DataSet/FEMNIST/leaf-master/leaf-master/models/server.py", line 72, in update_model
    base = [0] * len(self.updates[0][1])
**IndexError: list index out of range**

Any ideas welcome.

**Comment by colin-byrneireland** [comment]
Sorry forgot to mention that I just used the default code no modifications at all. Not sure if I'm doing a prep step wrong, compatibility issue or issue with the default code ?

Thks Colin . . .

**Comment by Sun-Shuai** [comment]
I have the same problem.

**Comment by Shilpa-Rani** [comment]
Did anyone find a solution to this? :(

**Comment by Alfons0329** [comment]
Same for CNN in celebA, maybe it is the common bug for image-based claaification?

**Comment by MakingL** [comment]
I also got an error when running `python main.py -dataset femnist -model cnn -lr 0.06 --minibatch 0.1 --clients-per-round 3 --num-rounds 2000`. 

My running environment is docker. I successfully generated data by `leaf/data/femnist/ $> ./preprocess.sh -s niid --sf 0.05 -k 0 -t sample --smplseed 1549786595 --spltseed 1549786796`, but got an error when running the model:

![leaf](https://user-images.githubusercontent.com/31580426/85243127-8bec9d80-b473-11ea-920d-4425183f6b93.png)

**Comment by tdye24** [comment]
> I also got an error when running `python main.py -dataset femnist -model cnn -lr 0.06 --minibatch 0.1 --clients-per-round 3 --num-rounds 2000`.
> 
> My running environment is docker. I successfully generated data by `leaf/data/femnist/ $> ./preprocess.sh -s niid --sf 0.05 -k 0 -t sample --smplseed 1549786595 --spltseed 1549786796`, but got an error when running the model:
> 
> ![leaf1](https://user-images.githubusercontent.com/31580426/85243336-34026680-b474-11ea-9685-bf0ce1bc5f75.png)
> 
> ![leaf2](https://user-images.githubusercontent.com/31580426/85243436-73c94e00-b474-11ea-85d3-2c7f8c900b07.png)
> 
> ![leaf](https://user-images.githubusercontent.com/31580426/85243127-8bec9d80-b473-11ea-920d-4425183f6b93.png)

Refer to my request.[https://github.com/TalwalkarLab/leaf/pull/39](url)

**Comment by tdye24** [comment]
> When I run python main.py -dataset femnist -model cnn -lr 0.06 --minibatch 0.1 --clients-per-round 3 --num-rounds 20
> 
> I get the following
> ![image](https://user-images.githubusercontent.com/44531236/71667242-2b01c980-2d5c-11ea-86c7-178f1e246d38.png)
> 
> ======================End of Report==========================
> Clients in Total: 0
> --- Random Initialization ---
> --- Round 1 of 20: Training 3 Clients ---
> Traceback (most recent call last):
> File "main.py", line 186, in
> main()
> File "main.py", line 87, in main
> server.update_model()
> File "/mnt/c/ul/ai/Thesis/DataSet/FEMNIST/leaf-master/leaf-master/models/server.py", line 72, in update_model
> base = [0] * len(self.updates[0][1])
> **IndexError: list index out of range**
> 
> Any ideas welcome.

I think, you didn't load the dataset properly.
