### ISSUE TITLE
failed to replicate the results

### ISSUE THREAD

**Issue by youyeg** [TalwalkarLab/leaf#23]
I have ubuntu 16.04 with two GPUs, and I did these steps, but it fails to perform paper_experiments

1. conda create --name leafenv python=3.5
2. git clone  https://github.com/TalwalkarLab/leaf
3. pip3 install -r requirements.txt
4. ./paper_experiments/femnist.sh

but after some rounds with zero 

`
 s
Failed to import the site module
Traceback (most recent call last):
  File "/lib/python3.5/site.py", line 703, in <module>
    main()
  File "/lib/python3.5/site.py", line 670, in main
    virtual_install_main_packages()
  File "/lib/python3.5/site.py", line 553, in virtual_install_main_packages
    f = open(os.path.join(os.path.dirname(__file__), 'orig-prefix.txt'))
`

`mv: cannot stat 'sys_metrics.csv': No such file or directory`

`mv: cannot stat 'stat_metrics.csv': No such file or directory`

**Comment by oscarciceri** [comment]
did you find a solution to this? I have the same problem

**Comment by tdye24** [comment]
> I have ubuntu 16.04 with two GPUs, and I did these steps, but it fails to perform paper_experiments
> 
> 1. conda create --name leafenv python=3.5
> 2. git clone  https://github.com/TalwalkarLab/leaf
> 3. pip3 install -r requirements.txt
> 4. ./paper_experiments/femnist.sh
> 
> but after some rounds with zero
> 
> `s Failed to import the site module Traceback (most recent call last): File "/lib/python3.5/site.py", line 703, in <module> main() File "/lib/python3.5/site.py", line 670, in main virtual_install_main_packages() File "/lib/python3.5/site.py", line 553, in virtual_install_main_packages f = open(os.path.join(os.path.dirname(__file__), 'orig-prefix.txt'))`
> 
> `mv: cannot stat 'sys_metrics.csv': No such file or directory`
> 
> `mv: cannot stat 'stat_metrics.csv': No such file or directory`

The names of generated files are **metrics_stat** and **metrics_sys**，you just need to rename them.

**Comment by janesser** [comment]
Complete walkthrough works for me like
```
git checkout https://github.com/TalwalkarLab/leaf
cd leaf
conda create --name leafenv python=3.5
conda activate leafenv
conda install gcc_linux-64 gxx_linux-64
pip3 install -r requirements.txt
cd data/femnist/
./preprocess.sh
cd ../../paper_experiments
./femnist.sh
```

Then sampling of data begins...
